services:
  - type: web
    name: codesync-backend
    env: node
    buildCommand: npm install
    startCommand: npm start

    envVars:
      - key: NODE_ENV
        value: production

      - key: BACKEND_URL
        value: https://codesync-real-time-collaborative-code-0y4g.onrender.com

      - key: CLIENT_URL
        value: https://YOUR-FRONTEND.vercel.app

      - key: GOOGLE_CLIENT_ID
        sync: false

      - key: GOOGLE_CLIENT_SECRET
        sync: false

      - key: JWT_SECRET
        sync: false

      - key: MONGO_URI
        sync: false